---
redcap_admin_manage: true
redcap_admin_manage_password: true
redcap_admin_hide_sensitive_logs: true

redcap_admin_username: redcap_admin
redcap_admin_email: "admin@{{ redcap_org_domain | default('example.test') }}"
redcap_admin_first_name: REDCap
redcap_admin_last_name: Admin

redcap_admin_revoke_default_site_admin: true
redcap_admin_default_site_admin_username: site_admin

redcap_web_parent_dir: /var/www/html
redcap_web_root: "{{ redcap_web_parent_dir }}/redcap"

redcap_admin_php_bin: /usr/bin/php
redcap_admin_password_reset_local_path: "{{ playbook_dir }}/../scripts/reset-redcap-password.php"
redcap_admin_password_reset_remote_path: "{{ redcap_web_root }}/reset-redcap-password.php"
redcap_admin_remove_password_reset_script: true
